version: '3.3'

services:
  mysql_db:
    image: mysql:8
    container_name: mysql_db_container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    # ports:
    #   - 3307:3306
    # expose:
    #   - ${DB_PORT}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
      # - ./data:/var/lib/mysql
      - mysql-data:/var/lib/mysql
    env_file:
      - .env
    # networks:
    #   - db_network

volumes:
  mysql-data:

# networks:
#   db_network:
