version: "3"

services:

  fluentd:
    container_name: fluentd_container
    image: fluent/fluentd:v1.3.2-1.0
    volumes:
      - ./fluentd/config:/fluentd/etc
      - ./fluentd/log:/fluentd/log
    restart: always
    ports:
      # - "24220:24220"
      # - "24220:24220/udp"
      - "24224:24224"
      - "24224:24224/udp"