version: "3"

services:

  fluentd:
    container_name: fluentd_s3_container
    build: ./fluentd
    volumes:
      - ./fluentd/config:/fluentd/etc
      - ./fluentd/log:/fluentd/log
    restart: always
    ports:
      - "24224:24224"
      - "24224:24224/udp"